name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: system upgrade
        run: sudo apt-get update && sudo apt upgrade -y && sudo apt-get install xvfb -y && sudo apt-get install ubuntu-desktop -y
      
      - name: install openssh-server
        run: sudo apt-get install openssh-server

      - name: start ssh-server
        run: sudo systemctl start ssh

      - name: ufw config
        run: sudo ufw allow ssh && sudo ufw enable && sudo ufw status

      - name: login info
        run: echo $USER && echo $(netstat -rn)
        
      - name: sleep
        run: sleep 10000
        

        
