name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: system upgrade
        run: |
          apt-get update && apt upgrade

      - name: downloading rustdesk
        run: wget -O rustdesk.deb https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.deb

      - name: installing rustdesk
        run: apt-get install ./rustdesk.deb -y
        
        name: running rustdesk
        run: rustdesk 

        
