name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: system upgrade
        run: sudo apt-get update && sudo apt upgrade -y && sudo apt-get install xvfb -y && sudo apt-get install ubuntu-desktop -y
      
      - name: config display
        run: export DISPLAY=:0
        
      - name: downloading rustdesk
        run: wget -O rustdesk.deb https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.deb

      - name: installing rustdesk
        run: sudo apt-get install ./rustdesk.deb -y
        
      - name: running rustdesk --get-id
        run: sudo rustdesk --password almid0n#mil0d0n && sudo rustdesk --get-id

      - name: sleep
        run: sleep 10000
        

        
